





package sadhanapharmacy;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.*;
import net.proteanit.sql.DbUtils;





public class Sales extends javax.swing.JFrame {


    Connection  con;
    String      url;
     
    PreparedStatement pst;
    Statement   st;
    ResultSet   rs;
    
    Float rev;
    private String temp;
    
    
    
    
    public Sales() {
        
        initComponents();
        
        setFullScreen();
        
        database();
        
        updateSales();
        
        updateTable();
        
        
        
        initialRevenueFor();
    }
      
    private void setFullScreen() {
        Toolkit kit = Toolkit.getDefaultToolkit();
        Dimension screenSize = kit.getScreenSize();
        setSize(screenSize.width, screenSize.height);
    }
    
  
    private void database() {
        
        try{
            //url = "jdbc:ucanaccess://D:/Programming/Netbeans Projects/SadhanaPharmacy/SP.mdb";
            url = "jdbc:ucanaccess://SP.mdb";
            con = DriverManager.getConnection(url); 
            
            
        }catch(Exception e){
            System.out.println("Could Not Connect to Database" +e);
        }   
    }
    
    
    
    private void revenuefor(String searchby){
        try{
            st = con.createStatement();
            String sql1 = "Select SUM(Revenue) AS TotalRev from Revenue Where Day Like '"+searchby+"%'";
            rs = st.executeQuery(sql1);
            
            
            if(rs.next()){
            
            tfRevenueFor.setText(rs.getString("TotalRev"));
            
            }
        }catch (Exception e){
                
        }
    }
    
    private void initialRevenueFor(){
        try{
            st = con.createStatement();
            String sql1 = "Select SUM(Revenue) AS TotalRev from Revenue";
            rs = st.executeQuery(sql1);
            
            
            if(rs.next()){
            
            tfRevenueFor.setText(rs.getString("TotalRev"));
            
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
    
    
    
    
    
    
    
   
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lBack = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfRevenue = new javax.swing.JTextField();
        lSetDate = new javax.swing.JLabel();
        tfSetDate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRevenue = new javax.swing.JTable();
        lItems = new javax.swing.JLabel();
        tfSearchBy = new javax.swing.JTextField();
        lSearchBy = new javax.swing.JLabel();
        bSave = new javax.swing.JButton();
        tfRevenueFor = new javax.swing.JTextField();
        lRevenueFor = new javax.swing.JLabel();
        bDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sales");
        getContentPane().setLayout(null);

        lBack.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        lBack.setForeground(new java.awt.Color(51, 51, 255));
        lBack.setText("Back");
        lBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lBackMouseClicked(evt);
            }
        });
        getContentPane().add(lBack);
        lBack.setBounds(55, 11, 40, 22);

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel1.setText("Revenue                                                                       Rs");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(424, 80, 359, 18);

        tfRevenue.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        tfRevenue.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfRevenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRevenueActionPerformed(evt);
            }
        });
        getContentPane().add(tfRevenue);
        tfRevenue.setBounds(794, 74, 123, 30);

        lSetDate.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        lSetDate.setText("Set Today's Date (Year Month Day)");
        getContentPane().add(lSetDate);
        lSetDate.setBounds(424, 130, 221, 18);

        tfSetDate.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        getContentPane().add(tfSetDate);
        tfSetDate.setBounds(794, 124, 121, 30);

        tblRevenue.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        tblRevenue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Date", "Revenue"
            }
        ));
        tblRevenue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRevenueMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRevenue);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(370, 300, 590, 223);

        lItems.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        lItems.setForeground(new java.awt.Color(51, 51, 255));
        lItems.setText("Items");
        lItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lItemsMouseClicked(evt);
            }
        });
        getContentPane().add(lItems);
        lItems.setBounds(124, 11, 45, 22);

        tfSearchBy.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        tfSearchBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchByActionPerformed(evt);
            }
        });
        tfSearchBy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfSearchByKeyTyped(evt);
            }
        });
        getContentPane().add(tfSearchBy);
        tfSearchBy.setBounds(750, 250, 160, 30);

        lSearchBy.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        lSearchBy.setText("Search By Date (Year Month Day)");
        getContentPane().add(lSearchBy);
        lSearchBy.setBounds(430, 250, 279, 30);

        bSave.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        bSave.setForeground(new java.awt.Color(0, 153, 51));
        bSave.setText("Save");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });
        getContentPane().add(bSave);
        bSave.setBounds(560, 180, 94, 37);

        tfRevenueFor.setEditable(false);
        tfRevenueFor.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        tfRevenueFor.setForeground(new java.awt.Color(0, 153, 51));
        tfRevenueFor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tfRevenueFor);
        tfRevenueFor.setBounds(723, 556, 110, 30);

        lRevenueFor.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lRevenueFor.setForeground(new java.awt.Color(0, 153, 51));
        lRevenueFor.setText("Total Revenue               Rs");
        getContentPane().add(lRevenueFor);
        lRevenueFor.setBounds(472, 560, 233, 22);

        bDelete.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        bDelete.setForeground(new java.awt.Color(255, 0, 51));
        bDelete.setText("Delete");
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(bDelete);
        bDelete.setBounds(690, 180, 89, 37);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    
    private void lBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lBackMouseClicked
        new Home().setVisible(true);
        dispose();
    }//GEN-LAST:event_lBackMouseClicked

    
    
    
    
    
    
    private void tfRevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRevenueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRevenueActionPerformed

    
    
    
    
    private void tblRevenueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRevenueMouseClicked
        try{
            int row = tblRevenue.getSelectedRow();
            
            String Table_click = (tblRevenue.getModel().getValueAt(row, 0).toString());
            
            String sql = "Select * from Revenue Where Day = '" + Table_click + "'";
            
            
            rs = st.executeQuery(sql);
            
            if(rs.next()){
                
                tfRevenue.setText(rs.getString("Revenue"));
                
                tfSetDate.setText(rs.getString("Day"));
                
             }
            
        }catch(Exception e){ 
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }//GEN-LAST:event_tblRevenueMouseClicked

    
    
    
    
    private void lItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lItemsMouseClicked
        new Items().setVisible(true);
        dispose();
    }//GEN-LAST:event_lItemsMouseClicked

    
    
    
    
    private void tfSearchByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchByActionPerformed
        
    }//GEN-LAST:event_tfSearchByActionPerformed

    
    
    
    
    
    private void tfSearchByKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchByKeyTyped
        String searchby = tfSearchBy.getText();

        try{

            st = con.createStatement();
            String sql = "Select Day, Revenue From Revenue Where Day Like '" + searchby + "%'";

            rs = st.executeQuery(sql);

            tblRevenue.setModel(DbUtils.resultSetToTableModel(rs));
            
                 
            revenuefor(searchby);
            
    
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
        
        
        
    }//GEN-LAST:event_tfSearchByKeyTyped

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        try{
            
            
            String setdate = tfSetDate.getText().trim();
            Float revenue = (Float.parseFloat(tfRevenue.getText().trim()));
            
            String sql = "Insert Into Revenue (Day, Revenue)"
                    + "Values ('" + setdate + "','" + revenue + "')";
            
            st = con.createStatement();
            
            st.executeUpdate(sql);
            con.commit();
            
            updateTable();
            deleteSales();
            initialRevenueFor();
            
            JOptionPane.showMessageDialog(null, "Entry Saved");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_bSaveActionPerformed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        
        try{
            String day = tfSetDate.getText().trim();
            Float revenue = Float.parseFloat(tfRevenue.getText().trim());
            
            String sql = "Delete from Revenue where Day = '" + day +  "' And Revenue = '" + revenue + "'";
            
            st = con.createStatement();
            st.executeUpdate(sql);
            con.commit();
            updateTable();
            JOptionPane.showMessageDialog(null, "Entry Deleted.");
            initialRevenueFor();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
         
    }//GEN-LAST:event_bDeleteActionPerformed


    
    
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        
        
        
       
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lBack;
    private javax.swing.JLabel lItems;
    private javax.swing.JLabel lRevenueFor;
    private javax.swing.JLabel lSearchBy;
    private javax.swing.JLabel lSetDate;
    private javax.swing.JTable tblRevenue;
    private javax.swing.JTextField tfRevenue;
    private javax.swing.JTextField tfRevenueFor;
    private javax.swing.JTextField tfSearchBy;
    private javax.swing.JTextField tfSetDate;
    // End of variables declaration//GEN-END:variables

    private void updateSales() {
        try{
            st = con.createStatement();
            String sql = "Select SUM(Revenue) from Sales";
            rs = st.executeQuery(sql);
            
        while (rs.next())
            temp = rs.getString(1);
        
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        tfRevenue.setText(temp);
    }

    private void updateTable() {
        try{
       
            st = con.createStatement();
            String sql = "Select Day, Revenue from Revenue Order By Day";
            rs = st.executeQuery(sql);
        
       
            tblRevenue.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void deleteSales() {
        try{
            st = con.createStatement();
            String sql = "Delete from Sales";
            st.executeUpdate(sql);
            updateSales();
            tfRevenue.setText(" ");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    } 
            
}